### ISSUE TITLE
improve compile instructions

### ISSUE THREAD

**Issue by NikoKrause** [B00merang-Project/LinXP#1]
Hey,

for me (Linux Mint 18.1) the command `./compile_icon_theme.py` does not work.
It says `/bin/python not found`.

I get it to compile with `python3 compile_icon_theme.py`.

**Comment by ndwarshuis** [comment]
yes, you need python 3. README updated and script now should force python 3 (3dc8e6fbc2653b2a922c096e8566d982c037d93e)
