### ISSUE TITLE
Missing icons in Linux Mint Cinnamon

### ISSUE THREAD

**Issue by NikoKrause** [B00merang-Project/LinXP#3]
In the menu there are 3 applications without icons:
(translated, not sure if those are exactly called like this)
1. Input method
2. USB Image Creator
3. USB Stick Format

Maybe you could add them or add Mint-X-yellow to inherits in the index.theme file?

**Comment by ndwarshuis** [comment]
adding Mint-X-Yellow is a good idea (29a2d7f0e6d0cb0b63abce48ad380f696a70fa0a)

not exactly sure to what you are referring so plz confirm this commit solves the issue

**Comment by dominichayesferen** [comment]
@petrucci4prez Mind if you bring the system tray icons from XP to this icon set?
Elbullazul also did the same thing with his YlmfOS Reworked Icon Set, so you could check there too.

**Comment by ndwarshuis** [comment]
@NikoKrause I take back what I said about the Mint-X-Yellow; linking this as fallback will require every app in the Mint-X series to have it's own XP icon (not going to happen...way easier just to use the default icons installed by each app in hicolor). Per you question, please post a screenshot of the offending icons (both Mint-X and LinXP) so I know where to look

@feren depends on what you mean by system tray...some of the icons in question with the WinXP theme are pngs masquerading as symbolic icons. Technically, symbolic icons are standardized as recolorable svgs (see [here](https://github.com/GNOME/gnome-icon-theme-symbolic)) and apps that use them expect to be able to change their color however they please (eg white on black background, which could look bad if the icon is a png that is always dark).

I'm not a fan of breaking said standard, although I suppose the svg's could be changed to look more XP-like and still retain their flexibility

**Comment by dominichayesferen** [comment]
@petrucci4prez The icons at the bottom-right for Battery, WiFi and Sound...

**Comment by NikoKrause** [comment]
@petrucci4prez 
Can you explain why inheriting from Mint-X-Yellow is a bad idea?
Have to tested setting Mint-X-Yellow as last inherit?
```
Inherits=gnome,hicolor,Mint-X-Yellow
```
The order is important. First it will look in gnome, then in hicolor and last in Mint-X-Yellow

**Comment by NikoKrause** [comment]
The applets with missing icons are, the following (what the .desktop files says):
1. 
```
[Desktop Entry]
Name=Input method
Exec=mintlocale im
Icon=im-chooser
```
2.
```
[Desktop Entry]
Name=USB Image Writer
Icon=usb-creator
Exec=mintstick -m iso
```
3.
```
[Desktop Entry]
Name=USB Stick Formatter
Icon=usb-creator
Exec=mintstick -m format
```

They look like this (The top one is 1. and the right one is 3.)
![screenshot-area-2017-05-11-160849](https://cloud.githubusercontent.com/assets/8415124/25953619/3864fe90-3664-11e7-943d-60a0df009561.png)

**Comment by daemonspudguy** [comment]
@petrucci4prez @NikoKrause @Zerophase @bluedxca93 @Elbullazul @feren I have a good idea, until further notice, try inheriting the WinXP icons

**Comment by NikoKrause** [comment]
That makes no sence. WinXP isn't installed by default. So you'll need to install a second icon theme as well for LinXP.

**Comment by daemonspudguy** [comment]
Ohhhh, didn't think about that

**Comment by ndwarshuis** [comment]
@NikoKrause I guess I see your logic now, if that's the case then the apps won't get squarish icons from Mint-X (because those should all be in hicolor anyways). Only problem is that any icon LinXP doesn't have that hicolor or gnome also don't have will fall back to a silvery squarish icon (which will look weird) but this should mostly only happen for status and actions, as these are the categories that will likely be missing the most icons...at least in the short run. Eventually this will be a non-issue once LinXP is fully populated

@feren yes those are symbolic icons (if you are just talking about the wifi, sound, and battery applets). Those might be modified to be more xp-like in the future, but won't be getting pngs as they are in WinXP. Symbolic icons are lower on the priority list

**Comment by ndwarshuis** [comment]
4aaf4cad8874a4251a09dc94a0b66cac7a205ce2
a366a0c2f88a4a199bc8ed3e2fa67d211de66b61
