### ISSUE TITLE
keynavigation in nemo with LinXP icon theme is slow

### ISSUE THREAD

**Issue by NikoKrause** [B00merang-Project/LinXP#6]
That's a very weird bug (testing on LM18.2 Cinnamon)

Add the LinXP theme globally, i.e. in `/usr/share/icons`.
Now navigate through folder icon with keyboard, e.g. in /home folder. It is very slow.
Navigating through files is normal.

Also it's normal, when the icon theme is installed locally in `~/.icons`.

**Comment by ndwarshuis** [comment]
You'll need to elaborate more for me to reproduce. I understand the global install part. Where are you navigating and how do you define 'slow?' Also, the title implies this does not happen with the mouse?

**Comment by NikoKrause** [comment]
See video below. I installed LinXP globally. First I navigate in a normal opened window with the keyboard. The navigation is slow and if you do it fast it skips a few folders. If I open the same window as admin and navigate it's fast and you see each folder it passes.
This doesn't happen with a local install of LinXP. Also I just see this behaviour with LinXP. Other icon themes do not show this weird keynav bug. (Maybe it's because of the broken symlinks?)
https://streamable.com/qu3tt

**Comment by NikoKrause** [comment]
This is due to a bug in the folder-color-switcher extension for nemo. It's fixed in Linux Mint 19.
